# Generated by Django 5.2.2 on 2025-06-22 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrelmembership',
            name='carrel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrels.carrel'),
        ),
        migrations.AddField(
            model_name='carrelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='carrel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='carrels.carrel'),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentupvote',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='carrels.sharedcontent'),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carrels.sharedcontent'),
        ),
        migrations.AlterUniqueTogether(
            name='carrelmembership',
            unique_together={('user', 'carrel')},
        ),
        migrations.AlterUniqueTogether(
            name='contentupvote',
            unique_together={('content', 'user')},
        ),
    ]
